<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'APP_SECRET' => 'cd1289ea4242c86407778619d1040a6e',
  'DATABASE_URL' => 'mysql://aluvejsl_user:Nhlaka02IIWf3[pXS@127.0.0.1:3306/aluvejsl_aluveapp?serverVersion=mariadb-10.4.24&charset=utf8mb4',
  'GOOGLE_API_KEY' => '',
  'GOOGLE_CLIENT_ID' => '',
  'GOOGLE_CLIENT_SECRET' => '',
  'APP_TIMEZONE' => 'Africa/Johannesburg',
);
